### PR TITLE
Ckeditor 4.4.8 and a builder for next releases

### PR DESCRIPTION
**Pull request by gotcha**
Upgrade Ckeditor to 4.4.8
Add scripts to automate update of ckeditor

### CODE REVIEW

**Comment by gbastien** [comment]
Hi @gotcha 

I tested a little and it seems that some plugins are missing, if I activate every buttons, some do not show like :
- spellchecker
- Scayt (scayt is missing in directory "plugins")

Maybe is it no more builtin now?

+++

Gauthier

**Comment by gotcha** [comment]
Yup, scayt has disappeared from

https://github.com/ckeditor/ckeditor-dev/tree/release/4.4.x/plugins

I should have checked the differences with

https://github.com/collective/collective.ckeditor/tree/master/src/collective/ckeditor/_src/ckeditor/plugins

@gbastien can you extend https://github.com/collective/collective.ckeditor/tree/builder/dev/build-ckeditor to add the missing plugins ?

**Comment by gbastien** [comment]
Hi @gotcha 

actually I prefer you adapt the script ;-), I do not want to spend to much time discovering what it does.

What I just wanted to underline is that full presets release are left available, for example : http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.4.8/ckeditor_4.4.8_full.zip

This way you are sure to get the right full preset, it can evolve (http://ckeditor.com/presets).

Then the builder script could "just" take care to grab extra plugins (or we can do it manually double-checking version compatibility).  We need to check the _full preset, especially regarding the default selected skin that seems to be "Moono" instead of "Moono color"...

So :
- download full preset release;
- change (download it and patch the build-config.js);
- download extra plugins manuall...

?
Gauthier

**Comment by gotcha** [comment]
I'll look at this when I'll have time.

**Comment by gbastien** [comment]
Hi @gotcha 

to me a "manual recipe" is not a problem, PR review will cover this.

Downloading the full release will make sure we have relevant things and not create our builder script (if I look here, I do not want : https://github.com/ckeditor/ckeditor-dev/blob/master/dev/builder/build.sh).

We may write a script just receiving the CKEditor version we want and :
- download it;
- patch it so we use "Moono color" skin;
- download relevant list of plugins (for example, image2 is at http://download.ckeditor.com/image2/releases/image2_4.4.8.zip, such kind of link may be generated for different addons);
- merge all this together...

We may work on this too if you are ok with this approach.

Gauthier

**Comment by gotcha** [comment]
The approach I took is to use ckbuilder from the ckeditor team:

https://github.com/collective/collective.ckeditor/blob/74b979030e706cf942d9304bae1db0df4c9e00da/dev/build-ckeditor/build.sh

The problem I have with doing clicks is that it is too easy to forget steps.

For instance, I had forgotten `scayt` was important for you and did not check it.

By scripting the release, we will be able to get the fixes from ckeditor quicker as well.

**Comment by gbastien** [comment]
@gotcha 

I am ok to script, but what I propose is to use the release the CKEditor team builds because we do not know what could change in the future...

Script the fact to get the release, "sed" it to "Moono color", script the the fact to get plugins and to merge it in the release, ...

Gauthier

**Comment by gotcha** [comment]
Once again, if you check my code, I am not building a new `ckbuilder`.

**Comment by gbastien** [comment]
I do not know what is the best solution, we just need regular updates and release I think.

Anyway, if tests with version 4.5.3 are ok, we can just forget about 4.4.8 also...

See you,

Gauthier

**Comment by gotcha** [comment]
@gbastien Can you check if c.ckeditor works for you now ?

scayt needs to be enabled by installing the plugin. Was it the case previously ?

**Comment by gbastien** [comment]
Hi @gotcha 

what do you mean by "installing the plugin"?  Scayt is available if you download the full version of ckeditor and will be activated together with ckeditor and other plugins.  Isn't it the case anymore?

+++

Gauthier

**Comment by gotcha** [comment]
I am asking if installing collective.ckeditor was enough for scayt to be enabled. Or if you had anything else to do ?

**Comment by gotcha** [comment]
@gbastien  Ok, scayt plugin used to be loaded without any config change. I have fixed the build process.

**Comment by gotcha** [comment]
Merged with #46

**Pull request closed without merging**
