### PR TITLE
Update ckeditorview.py

### PR DESCRIPTION
**Pull request by davidamoros**
Add support for Plone 4.1

### CODE REVIEW

**Comment by gbastien** [comment]
Hi @davidamoros 

the Plone 4.2 build is broken, it is not that important as I intended to remove the Plone 4.2.x build in Travis, but regarding this PR, I suppose this could be interesting to activate the Plone 4.1.x build and makes it work?

What do you think?

Gauthier

**Comment by davidamoros** [comment]
Hello @gbastien, Yes, this could be interesting. As said, this change was all I needed to make it work on Plone 4.1 (and python 2.6), but would be good to run all the integration tests.

Thank you!!

**Comment by gbastien** [comment]
Hi @davidamoros 

builds now pass for Plone 4.2 and 4.3, no time to do this pass for Plone 4.1 so as the code you changed is tested (at least touched by the tests), I will merge.

Gauthier

**Comment by davidamoros** [comment]
Thanks @gbastien !

**Pull request merged**
