### PR TITLE
Update CKEditor to 4.4.8

### PR DESCRIPTION
**Pull request by gotcha**

### CODE REVIEW

**Comment by gbastien** [comment]
Hi @gotcha 

just tried this and everything works as expected, is it ready to merge or a pending work?

Gauthier

**Comment by gotcha** [comment]
@spereverde is currently testing it. She will come back to us when she is done.

**Comment by gbastien** [comment]
@gotcha right, I am testing it too, I am currently extending the "specialchar" plugin, everything seem right until now...

I will need a new release next week including the extra plugins I mentionned, I will do a separate PR than my previous, I will close this previous right now.

See you,

Gauthier

**Comment by gbastien** [comment]
Hi @gotcha 

ready to merge so we can go on with this?

Thank you,

Gauthier

**Comment by gotcha** [comment]
@spereverde has an issue with their custom toolbar. IOW, there is still a hidden problem.

If you need a release now, I suggest two solutions:

- you make a private release on your egg server `collective.ckeditor==4.3.1+imio`
- we make a beta release on pypi

**Comment by gotcha** [comment]
This is what @spereverde told me:

> I can't find other strange things besides the toolbar button settings not working for now.
> I do feel that there is an issue somewhere with the available toolbar buttons.
> I tested several things but can't find a solution, it seems like some plugins aren't installed by default or the way the toolbar is set has changed, but need to look into it more.

**Comment by spereverde** [comment]
When selecting the full toolbar in the settings, a lot of buttons simply do not show (in our setup)
 33 CKEDITOR_FULL_TOOLBAR = """[
 34     ['Source','-','AjaxSave','Preview','-','Templates'],
 35     ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Print',
 36     'SpellChecker', 'Scayt'],
 37     ['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],
 38     ['Styles','Format','Font','FontSize','TextColor','BGColor'],
 39     '/',
 40     ['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
 41     ['NumberedList','BulletedList','-','Outdent','Indent','Blockquote','CreateDiv'],
 42     ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','BidiLtr','BidiRtl'],
 43     ['Link','Unlink','Anchor'],
 44     ['Image','Flash','Table','HorizontalRule','Smiley','SpecialChar',
 45     'PageBreak','Iframe'],
 46     ['Maximize', 'ShowBlocks','-','About']
 47 ]""" 
Following buttons not showing up when editing a page (new or existing):
[
     ['Preview','-','Templates'],
     ['Print', 'SpellChecker'],
     ['Find','Replace','-','SelectAll'],
     ['Font','FontSize','TextColor','BGColor'],
     '/',
     ['CreateDiv'],
     ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','BidiLtr','BidiRtl'],
     ['Flash','Smiley','PageBreak','Iframe'],
     ['ShowBlocks']
 ]

**Comment by gbastien** [comment]
Hi @ gotcha,

I just tried to activate the full bar with this PR and indeed, most of buttons do not show up... with this branch ck4.4.8, but trying with my fork (https://github.com/gbastien/collective.ckeditor) it works as expected, when selecting the "fullbar", every buttons are shown.

Could you please validate this version with @spereverde ?  Or look what is the difference between both versions?

Thank you!

Gauthier

**Comment by gbastien** [comment]
@gotcha I think this is related :

https://github.com/collective/collective.ckeditor/pull/43/files#diff-0ce82618ce4dbdc48d03fc2206fc250cL29

Gauthier

**Comment by gotcha** [comment]
I cherry-picked tests and minor changes onto master.

I opened a new pull request for CKEditor 4.4.8
@gbastien @spereverde Can you test #44 ?

**Pull request closed without merging**
