### PR TITLE
Plone5

### PR DESCRIPTION
**Pull request by veritazx**
Thanks for providing the plone5 branches. We were really looking forward to this as we are preparing to switch to Plone 5 and did not want to make our editors learn a new editor.
Unfortunately, there is still work to do. There is a remaining portal_properties - lookup in the branch, which is fixed by this PR. And we are currently working on a prototype on Plone 5.2.4, that needs the new utility configuration to be optional.

Let me know if we can help to push those branches to completion and release :)

Thanks a lot for your work!

### CODE REVIEW

**Comment by gotcha** [comment]
I missed the notification of this PR. Sorry.
It is nevertheless a bit sad that you did not speak to us: https://github.com/collective/collective.ckeditor/tree/registry

We plan to merge and release this code for Plone 4.3.

And rebase plone5 branch later.

**Comment by veritazx** [comment]
My PR is from our fork back into Plone5, so there should not be any problems with the rebase. :) 
We would like to add some more changes (especially configurability of the toolbars, including dynamic number of toolbars). I'll try to create single PRs per feature.

**Comment by veritazx** [comment]
Sorry, misunderstood. So my changes either already are in the registry branch or should go in there, right?

**Comment by gotcha** [comment]
> ... add some more changes (especially configurability of the toolbars, including dynamic number of toolbars). I'll try to create single PRs per feature.

Check the  current code, there is already some configurability of toolbar. Not sure what you mean with dynamic number of toolbars.

**Comment by gotcha** [comment]
This feature is not well documented.

Toolbars can be registered like here:

https://github.com/collective/collective.ckeditor/blob/583cd3a3728c081f5318bec47d1e53f38d3ca8ee/src/collective/ckeditor/profiles/default/registry.xml#L10

Then it is possible to specify different toolbar for different widgets.

For instance with:
```
from plone.app.form.widgets.wysiwygwidget import WYSIWYGWidget

class TextOnlyWidget(WYSIWYGWidget):
    settings = dict(toolbar="header")
```

**Comment by veritazx** [comment]
We went back to adding all our changes to our fork. Sorry. 
I'm thus closing this PR as it doesn't make any sense in that form. 
I'll try to push some of the commits into the branches where they belong in small portions so review can take place.

**Pull request closed without merging**
